# Getting Help with 432

Data science and statistical programming can be difficult. Computers are stupid and little errors in your code can cause hours of frustration (even if you've been doing this stuff for years!). **You shouldn't spend more than 15 minutes struggling with anything in this class without asking for help.**

Once the course begins, you have several ways to get help from us:

## TA Office hours provide one-on-one help

We have eight dedicated and capable [Teaching Assistants][Teaching Assistants] working with us this term. More [information on the TAs is available here][Teaching Assistants].

You are strongly encouraged to visit the Teaching Assistants during office hours that are convenient for you, whenever you need help with the course. This is the best way to get one-on-one help, or try out a new idea.

TA office hours will be held exclusively via zoom. They begin on Monday 2022-01-17 and continue through Sunday 2022-04-24, other than during Spring Break. Zoom information to join these sessions will be found on [Canvas](https::/canvas.case.edu), and on our Shared Google Drive.

The weekly schedule of TA office hours follows:

Date | Time(s)
-----: | :---------
Sunday | 9:30 - 10:30 AM, 5:30 - 7:00 PM, 8:30 - 10:00 PM
Monday | 5:00 - 6:30 PM, 7:00 - 8:30 PM
Wednesday | Noon - 1:30 PM
Thursday | 6:00 - 7:30 PM
Friday | Noon - 1:00 PM
Saturday | 10:30 AM - Noon, 3:30 - 5:00 PM

Remember that [Piazza](https://piazza.com/case/spring2022/pqhs432) is available 24 hours a day, 7 days a week for your questions and answers.

- Office Hours are held for your benefit. Please visit the TAs, especially if you have questions about how to do things in R, or about the content of the class slides or course notes. They're volunteering their time to help you, and most of them have been in your shoes in previous years. They want to help you!
  - More [information on the TAs is posted below][Teaching Assistants].

## Piazza is the place to ask questions 24/7

- We will use [Piazza](https://piazza.com/case/spring2022/pqhs432) this semester to facilitate questions and answers. We'll conduct all class-related discussion there, rather than via email.
- Find our class page at: https://piazza.com/case/spring2022/pqhs432. If you're successfully enrolled in the class, you should be able to sign up immediately.
  - The quicker you begin asking questions on Piazza (rather than via emails), the quicker you'll benefit from the collective knowledge of your classmates and instructors. 
  - We encourage you to ask questions when you're struggling to understand anything related to the class, and you can even do so anonymously.
  - You'll also be able to help your colleagues by answering their questions, as well.
  - We will use Piazza for all questions **except** questions about [Quizzes][Quizzes]. Information about getting help on the Quizzes will be provided as part of the instructions for each Quiz.

In addition, there are many, many online resources to help you learn R beyond those we provide. 

  - Googling effectively is an important skill that requires practice. Don't be afraid to use search engines to figure out how to code things in R, for example.
  - The [RStudio Community](https://community.rstudio.com/) is a forum specifically designed for people using RStudio and the tidyverse (and that will be you.)


## Meeting with Professor Love

Professor Love does not hold regular office hours. He will open Zoom 10 minutes before each class, and keep it open afterwards, as well, to address any concerns that you're willing to discuss there.

- If you have any unique concerns about the course, need special accommodations or have any other issues you want to discuss with Professor Love specifically, please email him (**Thomas dot Love at case dot edu**) and he'll respond as quickly as possible.
- Questions about course materials are best asked through [Piazza](https://piazza.com/case/spring2021/pqhs432) or at TA Office Hours.
