# Course Policies

## Emergency Policy

If you need to miss one session, or even two, just review the materials (including the recordings) and move on, and please feel encouraged to ask for help.

If an emergency arises that will keep you from timely completion of a lab, a project or a quiz, send an email directly to Dr. Love saying the following:

> I have an emergency that will keep me from completing (*list things you're worried about completing*) in a timely fashion. I will contact you again when I am able to make plans.

- Dr. Love will respond with "OK" and temporarily excuse you from things until **you** send a "re-connection" email to make plans for making up the work you missed, at which time he'll evaluate the situation and together you can make that plan. At no time do you owe us any information about your health or the nature of the emergency.

## Regrade Policy

Grades on projects and quizzes are completed by Dr. Love. For labs, TAs do all grading. Students are **requested not to dispute** any grading on Labs during the semester. Instead, should you receive a lower grade on a Lab than you feel you deserve based on the feedback the TA provides, the answer sketch and the grading rubric, you should submit a request for a regrade by Professor Love through the Google Form found at http://bit.ly/432-2022-lab-regrade-requests. You must log into Google via CWRU to see the form.

## Other Course Policies

1. Any concerns or questions regarding these general policies, the teaching assistants or the course itself should be directed to Professor Love, if at all possible.
2. All student work is subject to the University's policies and procedures. 
3. **Registration is required**. I do not permit anyone to audit the course who has not previously taken it, without exception. If you've taken the course before and want to sit in again, you will need to volunteer or be hired as a teaching assistant.
4. **Grading**. Students in this class are not in competition with each other for grades. I have no set percentage of students who will receive any particular grade.
5. **Attendance** is expected, but it is also expected that sometimes life will intervene. All students are expected to attend all class sessions, but if necessary, using the video recordings made available on Canvas to view each class before the next one is given.
    - If you need to miss two or more classes in a row, inform Professor Love via email beforehand, or as soon as possible thereafter. I will assume you have a good reason - details are **not** necessary.
    - You are responsible for all missed work, regardless of the reason for your absence. 
6. **Submissions** In this class, it is far better to turn in timely, but only partially complete work than nothing at all.
7. **Feedback on assignments - deadline.** On every assignment, Lab, Quiz, project-related task, whatever, we will be delighted to respond to questions **up to 12 hours before** the assignment is due. After that time, you may wind up on your own. The reason for this is that Professor Love and the teaching assistants will regularly post responses to frequently asked questions about assignments, and we need sufficient time to accomplish this task.
8. **On Getting Help Quickly and Effectively**: In general, we don't have a way to diagnose your problem with R, RStudio or Markdown if you don't show us what you're typing that causes an error, or a lack of results. If you wrote a Markdown file, we need to see it, along with a specific question (or series of them) about specific error messages or strange results you are getting. We need to replicate the problem in order to know how to fix your problem, and it also helps if we know what error message you're seeing, or what strange result you are getting.
10. **Distractions**. Please mute yourself during a Zoom class, unless you are asking a question, or working in a small group. We strongly prefer people to turn on their cameras, but do not requir this. The temptation to look at your phone or Facebook or email during class is nearly irresistible. Resist anyway, if only to avoid distracting your instructor and your fellow students. 
11. **Research Usage**. Any and all results of in-class and out-of-class assignments and activities are data sources for research and may be used in published research. All such use will always be anonymous.
12. **Recording.** We intend to provide video recordings of each class after they are complete. You should assume that anything you say or place in the Chat session during a Zoom class session *will* be recorded.
13. **Typos.** Professor Love makes occasional typographic and grammatical errors, which irritate him enormously. Please post in the relevant section of [Piazza](https://piazza.com/case/spring2022/pqhs432) if you find any in this syllabus or any other course materials. If you are the first to let us know, and we make the change, you will receive some credit in your class participation grade.

Again, all Case Western Reserve University policies apply to this class. To the extent that those policies are unclear, I would regard an appropriate code of conduct as mirroring  [this one from the R Consortium](https://github.com/RConsortium/RCDI-WG/blob/master/conduct/code-of-conduct.md).

## Frequently Asked Questions

### Can I audit the course?

No. Enrolled students and teaching assistants are the only people permitted to attend the course.

### Is it possible to take the course pass/fail?

No, it is not. However, no student in the past five years has received a final course grade other than A, B or Incomplete.

### How will I know how I'm doing in the class?

We aim for substantial and timely feedback from the teaching assistants and myself on all elements of the course.

### Does the 432 course assume we have completed 431?

Yes, it does. The materials from the 431 course are available to you until 2022-06-01 at https://thomaselove.github.io/431/.

### Do I have to be in Cleveland to take this course?

Yes. We hope that only the first four classes will be done via Zoom.

### Will all class materials be available to me online?

We'll try to make sure all sessions are video-recorded and made available to you after class, but we've had technical problems more than once in the past with that strategy, so we won't promise that will happen. All slides and many other materials will definitely be provided through the README for each class.

### How do I get connected to Zoom through CWRU?

The Zoom links for the semester's classes are available now through Canvas, and have also been emailed to your CWRU account if you are enrolled through SIS. 

### What if I lose my internet connection during a Zoom class?

That's part of the reason why each session will be recorded. If Dr. Love loses his, we'll pause until things get straightened out.
